# language: generic 

# super user permission required for this build
sudo: required

# tell travis CI that Docker CLI is needed
servies: 
  - docker

# series of steps/setup to run before running the test
before_install:
  - docker build -t auronsiow/docker-react -f Dockerfile.dev .

script:
  - docker run auronsiow/docker-react npm run test -- --coverage

# script:
#   - docker run -e CI=true USERNAME/docker-react npm run test -- --coverage
